name: Run Model Training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-model:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib seaborn requests
      - name: Configure matplotlib
        run: |
          echo "backend: Agg" > matplotlibrc
          export MPLBACKEND=Agg
      - name: Log setup time
        run: echo "Setup completed at $(date)"
      - name: Find Python script
        id: find-script
        run: |
          SCRIPT=$(ls *.py | head -n 1)
          echo "Found Python script: $SCRIPT"
          echo "script=$SCRIPT" >> $GITHUB_OUTPUT
      - name: Run training script
        run: |
          sleep 1
          python ${{ steps.find-script.outputs.script }} &
      - name: Wait and trigger next run
        run: |
          sleep 21240  # Wait ~354 minutes to ensure trigger
          echo "Triggering next workflow run"
        continue-on-error: true
      - name: Trigger self
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Context:', JSON.stringify(context, null, 2));
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const currentWorkflow = workflows.workflows.find(w => w.name === context.workflow);
            const workflowId = currentWorkflow ? currentWorkflow.path.split('/').pop() : 'test.yml';
            console.log(`Using workflow_id: ${workflowId}`);
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              ref: 'main'
            });
        continue-on-error: true
